import Foundation

public struct Strings {}

extension Strings {
    public static let AddBoomark                            = NSLocalizedString("Add bookmark", comment: "")
    public static let AddingVideo                           = NSLocalizedString("Adding video", comment: "")
    public static let AddMusic                              = NSLocalizedString("Add music", comment: "")
    public static let AddToPlaylist                         = NSLocalizedString("Add to playlist", comment: "")
    public static let Advice                                = NSLocalizedString("Advice", comment: "")
    public static let AirpodsMode                           = NSLocalizedString("Airpods Mode", comment: "")
    public static let AllowDownloadVideo                    = NSLocalizedString("Allow you to download a video", comment: "")
    public static let AppVersion                            = NSLocalizedString("App Version %@", comment: "")
    public static let AreYouSure                            = NSLocalizedString("Are you sure?", comment: "")
    public static let Artist                                = NSLocalizedString("Artist", comment: "")
    public static let ArtistCannotEmpty                     = NSLocalizedString("Artist cannot be empty", comment: "")
    
    public static let Bookmarks                             = NSLocalizedString("Bookmarks", comment: "")
    public static let Browser                               = NSLocalizedString("Browser", comment: "")
    
    public static let Cancel                                = NSLocalizedString("Cancel", comment: "")
    public static let CancelledExtractingAudio              = NSLocalizedString("Cancelled extracting audio", comment: "")
    public static let CantInsertEmptyData                   = NSLocalizedString("You can't insert empty data!", comment: "")
    public static let Clear                                 = NSLocalizedString("Clear", comment: "")
    public static let ClearPhoto                            = NSLocalizedString("Clear photo", comment: "")
    public static let ClearAllDataAndCookie                 = NSLocalizedString("Clear all data and cookie", comment: "")
    public static let Close                                 = NSLocalizedString("Close", comment: "")
    public static let Contact                               = NSLocalizedString("Contact", comment: "")
    public static let Cover                                 = NSLocalizedString("Cover", comment: "")
    
    public static let Delete                                = NSLocalizedString("Delete", comment: "")
    public static let DeletePlaylist                        = NSLocalizedString("Delete playlist", comment: "")
    public static let DeniedToRoll                          = NSLocalizedString("Denied to the roll", comment: "")
    public static let Description                           = NSLocalizedString("Description", comment: "")
    public static let Disable                               = NSLocalizedString("Disable", comment: "")
    public static let Done                                  = NSLocalizedString("Done", comment: "")
    public static let Download                              = NSLocalizedString("Download", comment: "")
    public static let Downloaded                            = NSLocalizedString("Downloaded", comment: "")
    public static let Downloading                           = NSLocalizedString("Downloading", comment: "")
    
    public static let Edit                                  = NSLocalizedString("Edit", comment: "")
    public static let Email                                 = NSLocalizedString("Email", comment: "")
    public static let EmailValid                            = NSLocalizedString("Must be a valid email address", comment: "")
    public static let EmptyInputData                        = NSLocalizedString("Empty input data", comment: "")
    public static let Enable                                = NSLocalizedString("Enable", comment: "")
    public static let End                                   = NSLocalizedString("End", comment: "")
    public static let Error                                 = NSLocalizedString("Error", comment: "")
    public static let ErrorSendingEmail                     = NSLocalizedString("Error sending email!", comment: "")
    public static let ExtractAudio                          = NSLocalizedString("Extract audio", comment: "")
    public static let ExtrationAudioInProgress              = NSLocalizedString("Extration audio in progress...", comment: "")
    
    public static let FailedExtractingAudio                 = NSLocalizedString("Failed extracting audio", comment: "")
    public static let FieldIsRequired                       = NSLocalizedString("This field is required", comment: "")
    public static let Filename                              = NSLocalizedString("Filename", comment: "")
    public static let FilenameAlreadyExistsOverride         = NSLocalizedString("Filename already exists. Override?", comment: "")
    public static let FilenameAlreadyPlaylistAssociated     = NSLocalizedString("The filename is contained in one or more playlists. Delete anyway?", comment: "")
    public static let FilenameCannotEmpty                   = NSLocalizedString("Filename cannot be empty", comment: "")
    public static let FilenameErrorMessage                  = NSLocalizedString("Please enter filename", comment: "")
    public static let FilesUploaded                         = NSLocalizedString("Files uploaded", comment: "")
    public static let FromYourComputer                      = NSLocalizedString("From your computer", comment: "")
    public static let Fullname                              = NSLocalizedString("Fullname", comment: "")
    
    public static let GoToSettings                          = NSLocalizedString("Go to settings -> %@ -> Photos -> Switch On", comment: "")
    
    public static let History                               = NSLocalizedString("History", comment: "")
    public static let HomePage                              = NSLocalizedString("Home Page", comment: "")
    public static let Hour                                  = NSLocalizedString("hour", comment: "")
    public static let Hours                                 = NSLocalizedString("%@ hours", comment: "")
    
    public static let Informations                          = NSLocalizedString("Informations", comment: "")
    
    public static let LoadFromRoll                          = NSLocalizedString("Load from roll", comment: "")
    
    public static let Minute                                = NSLocalizedString("a minute", comment: "")
    public static let Minutes                               = NSLocalizedString("%@ minutes", comment: "")
    public static let MissingInternetConnection             = NSLocalizedString("Sorry, there doesn’t seem to be an internet connection", comment: "")
    public static let Music                                 = NSLocalizedString("Music", comment: "")
    public static let MusicUsedSpace                        = NSLocalizedString("Music used space: %@", comment: "")
    
    public static let OK                                    = NSLocalizedString("OK", comment: "")
    public static let Other                                 = NSLocalizedString("Other", comment: "")
    
    public static let Name                                  = NSLocalizedString("Name", comment: "")
    public static let No                                    = NSLocalizedString("No", comment: "")
    
    public static let Pause                                 = NSLocalizedString("Pause", comment: "")
    public static let PhotoLibrary                          = NSLocalizedString("Photo library", comment: "")
    public static let PickAnOption                          = NSLocalizedString("Pick an option...", comment: "")
    public static let Play                                  = NSLocalizedString("Play", comment: "")
    public static let Playlist                              = NSLocalizedString("Playlist", comment: "")
    public static let PlaylistItem                          = NSLocalizedString("Playlist item", comment: "")
    public static let PlaylistTitle                         = NSLocalizedString("Playlist title", comment: "")
    public static let PleaseEnterArtist                     = NSLocalizedString("Please enter artist", comment: "")
    
    public static let RatingApp                             = NSLocalizedString("Rating App", comment: "")
    public static let Remove                                = NSLocalizedString("Remove", comment: "")
    public static let Rename                                = NSLocalizedString("Rename", comment: "")
    public static let ReportBugs                            = NSLocalizedString("Report bugs", comment: "")
    public static let Retry                                 = NSLocalizedString("Retry", comment: "")
    
    public static let Save                                  = NSLocalizedString("Save", comment: "")
    public static let SavedPhotos                           = NSLocalizedString("Saved photos", comment: "")
    public static let SaveToRoll                            = NSLocalizedString("Save to roll", comment: "")
    public static let SaveYouChanges                        = NSLocalizedString("Save you changes?", comment: "")
    public static let Second                                = NSLocalizedString("a second", comment: "")
    public static let Seconds                               = NSLocalizedString("%@ seconds", comment: "")
    public static let Send                                  = NSLocalizedString("Send", comment: "")
    public static let SearchEngine                          = NSLocalizedString("Search engine", comment: "")
    public static let SearchOrEnterAddress                  = NSLocalizedString("Search or enter address", comment: "")
    public static let Settings                              = NSLocalizedString("Settings", comment: "")
    public static let ShareFacebookPage                     = NSLocalizedString("Share Facebook page", comment: "")
    public static let SizeDownloaded                        = NSLocalizedString("%@ of %@ downloaded", comment: "")
    public static let Start                                 = NSLocalizedString("Start", comment: "")
    public static let SuccessExtractingAudio                = NSLocalizedString("Success extracting audio", comment: "")
    public static let SuccessSendingEmail                   = NSLocalizedString("Successfully sent email!", comment: "")
    public static let SorryDoesntInternetConnection         = NSLocalizedString("Sorry, there doesn't seem to be an internet connection", comment: "")
    
    public static let TakePhoto                             = NSLocalizedString("Take photo", comment: "")
    public static let Title                                 = NSLocalizedString("Title", comment: "")
    public static let TitleCannotEmpty                      = NSLocalizedString("Title cannot be empty", comment: "")
    public static let TitleErrorMessage                     = NSLocalizedString("Please enter title", comment: "")
    public static let ThirdPartySoftware                    = NSLocalizedString("Third Party Software", comment: "")
    public static let TypeMessage                           = NSLocalizedString("Type message", comment: "")
    
    public static let UnableExtractingAudio                 = NSLocalizedString("Unable extracting audio", comment: "")
    public static let UnknownErrorDuringExtractingAudio     = NSLocalizedString("Unknown error during extracting audio", comment: "")
    public static let Url                                   = NSLocalizedString("Url", comment: "")
    public static let Uploading                             = NSLocalizedString("Uploading", comment: "")
    public static let UploadFromBrowser                     = NSLocalizedString("Upload from browser", comment: "")
    
    public static let WaitingExtractingAudio                = NSLocalizedString("Waiting extracting audio (%@ %)", comment: "")
    public static let WantYouDownloadThisVideo              = NSLocalizedString("Want you download this video?", comment: "")
    
    public static let Video                                 = NSLocalizedString("Video", comment: "")
    public static let VideoDownloadedIsDisabledFromSettings = NSLocalizedString("Video downloads have been disabled in the Settings", comment: "")
    public static let VideoUnsuccessSaved                   = NSLocalizedString("Video can't be saved", comment: "")
    public static let VideoSuccessSaved                     = NSLocalizedString("Video was successfully saved", comment: "")
    public static let VideoUsedSpace                        = NSLocalizedString("Video used space: %@", comment: "")
    
    public static let Yes                                   = NSLocalizedString("Yes", comment: "")
}
